docs: remove privatekey: & user key -> shared key
atsign-foundation/at_protocol pull request #133
Opened 2024-02-14 15:16 UTC by JeremyTubongbanua

closes #131 

**- What I did**
- Removed privatekey: from the specification
- Also updated user key to be shared key

**- How I did it**

- See changes

2024-02-14 19:03 UTC, gkc requested changes

2024-02-14 19:03 UTC, gkc commented on specification/at_protocol_specification.md
> -3. User key
concept of private key still exists, but does not have an explicit scope of `privatekey:` - rather, it has no explicit scope - i.e. an example being `pk1@alice` - and is therefore interpreted as being private.

2024-02-14 19:03 UTC, gkc commented on specification/at_protocol_specification.md
> -3. User key
So section 2 still needs to exist - but needs to be reworded so it does not include the specific visibility scope of `privatekey:`

2024-07-15 21:47 UTC, XavierChanth commented
Added these changes to #166

2024-07-15 21:47 UTC, closed without merging