docs: added delete verb section
atsign-foundation/at_protocol pull request #82
Opened 2023-05-17 19:58 UTC by natt-n

**What I did**

Added the 'delete' verb section.

2023-05-17 20:00 UTC, JeremyTubongbanua approved these changes

2023-05-17 20:41 UTC, JeremyTubongbanua requested changes
In #81 , I added these headers to each verb (Synopsis, Syntax, Example, Response, Description, and Options).

Do you think we could do the same for the `delete` verb too?

2023-05-18 17:16 UTC, gkc submitted a review, later dismissed

2023-05-18 17:17 UTC, gkc commented
You need to resolve conflicts, @JeremyTubongbanua

2023-05-18 17:39 UTC, JeremyTubongbanua commented
> In #81 , I added these headers to each verb (Synopsis, Syntax, Example, Response, Description, and Options).
> 
> Do you think we could do the same for the `delete` verb too?

Done in https://github.com/atsign-foundation/at_protocol/pull/82/commits/ea42786a7ee854e630b7ec3187542372ae9855a7

2023-05-18 17:40 UTC, JeremyTubongbanua approved these changes, later dismissed

2023-05-18 17:41 UTC, JeremyTubongbanua commented
Also added the following in [commit](https://github.com/atsign-foundation/at_protocol/commit/ea42786a7ee854e630b7ec3187542372ae9855a7) 

- Syntax header
- Options table


Image Preview:
![image](https://github.com/atsign-foundation/at_protocol/assets/79019866/7aae181e-dd02-4aaa-ac35-5dd87ef5fa13)

2023-05-19 15:41 UTC, gkc requested changes

2023-05-19 15:41 UTC, gkc commented on specification/at_protocol_specification.md
> +```^delete:(?:cached:)?((?:public:)|(@(?<for@sign>[^@:\s]-):))?(?<atKey>[^:]((?!:{2})[^@])+)@(?<@sign>[^@\s]+)$```
That is not the latest regex. See https://github.com/atsign-foundation/at_tools/blob/trunk/packages/at_commons/lib/src/verb/syntax.dart#LL66C3-L72C12

2023-05-23 17:50 UTC, JeremyTubongbanua commented on specification/at_protocol_specification.md
> +```^delete:(?:cached:)?((?:public:)|(@(?<for@sign>[^@:\s]-):))?(?<atKey>[^:]((?!:{2})[^@])+)@(?<@sign>[^@\s]+)$```
See [af47555](https://github.com/atsign-foundation/at_protocol/pull/82/commits/af4755511dca6604b03557b5bcc18227c46e47d0)

2023-05-23 17:54 UTC, gkc approved these changes

2023-05-23 17:54 UTC, merged